spring:
  datasource:
    url: ${postgres-url}
    username: ${postgres-username}
    password: ${postgres-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: ${spring-allow}

keycloack:
  auth-server-url: ${keycloak-auth}
  realm: ${keycloak-realm}
  resource: ${keycloak-resource}
  public-client: ${keycloak-client}
  principal-attribute: ${keycloak.principal}

---

spring:
  datasource:
    url: ${postgres-url-hml}
    username: ${postgres-username-hml}
    password: ${postgres-password-hml}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: ${spring-allow-hml}
